baseURL = "/"
languageCode = "it"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    description = "esperienza di acquisto su amazon"
# Collaborative analysis on shopping experience and personalization algorithm"
    tagline = "Gli algoritmi non sono neutrali, pertanto dovrebbero essere sotto il controllo di noi utenti"

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90

 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 80


 [[menu.featured]]
    identifier = "parlare"
    name= "Parlare di algoritmi e di potere"
    url = "/parlare-di-algoritmi/"
    weight = -180
    pre = "/images/event.svg"
    post = "Come parlare di algoritmi? Le nostre prime esperienze divulgative"
 [[menu.featured]]
    identifier = "cosa"
    name = "Cosa c'è in Tracking Exposed"
    url = "/cosa-e-tracking-exposed/"
    weight = -170
    pre = "/images/box_bgorange.svg"
    post = "Amazon è solo l'ultima piattaforma, abbiamo iniziato con Faceobok, Youtube e Pornhub ;)"
 [[menu.featured]]
    identifier = "analisi"
    name = "La nostra analisi in dettaglio"
    url = "/analisi/"
    weight = -160
    pre = "/images/kindle.svg"
    post = "Le ricerche comparate, i prezzi che cambiano: riflessioni e metodologia, per rendere questi esperimenti replicabili"