baseURL = "/"
languageCode = "it"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    tagline = "A tool for algorithm analysts to look into Amazon's personalization."
    description = "Algorithm analysis based on passive data scraping of amazon pages. With our tools, researcher can collect evidences on dynamic pricing abuses and data discrimination."
    ourvision = false

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90

 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 80


 [[menu.featured]]
    identifier = "what"
    name = "What is it amTREX?"
    url = "/what-we-do/"
    weight = -180
    pre = "/images/event.svg"
    post = "Our first experiments and how the tool work."
 [[menu.featured]]
    identifier = "how"
    name= "How does it work"
    url = "/how-does-it-work/"
    weight = -170
    pre = "/images/box_bgorange.svg"
    post = "Beside Amazon, we enable analysis of Faceobok, Youtube, and Pornhub."
 [[menu.featured]]
    identifier = "kwnomore"
    name = "Know more"
    url = "/know-more/"
    weight = -160
    pre = "/images/kindle.svg"
    post = "Amazon personalized results, dynamic pricing and investigation on personal data."