baseURL = "/"
languageCode = "it"
title = "Amazon Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "amazon"
    subsite = "amazon"
    description = "Un'analisi dell'algoritmo di amazon, considerazioni sul trattamento dati personali ed il loro impatto su di noi. Parte di una trasmissione divulgativa"
    tagline = "Gli algoritmi controllano la tua esperienza online. Noi vorremmo che tu controllassi gli algoritmi."
    ourvision = false

[permalinks]
    posts = "/:slug/"

[menu]
 [[menu.main]]
    page = "Tracking Exposed"
    identifier = "trex"
    name = "Umbrella project: Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90

 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 80


 [[menu.featured]]
    identifier = "parlare"
    name= "Algoritmi e potere"
    url = "/parlare-di-algoritmi/"
    weight = -180
    pre = "/images/event.svg"
    post = "Le nostre prime esperienze divulgative"
 [[menu.featured]]
    identifier = "cosa"
    name = "Cosa c'è in Tracking Exposed"
    url = "/cosa-e-tracking-exposed/"
    weight = -170
    pre = "/images/box_bgorange.svg"
    post = "Oltre ad Amazon, abbiamo analizzato Faceobok, Youtube e persino Pornhub"
 [[menu.featured]]
    identifier = "analisi"
    name = "Per approfondire"
    url = "/analisi/"
    weight = -160
    pre = "/images/kindle.svg"
    post = "Le ricerche comparate, i prezzi che cambiano: riflessioni e metodologia, per rendere questi esperimenti replicabili"